version: 2.0
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: 4bb5dda707e00d442d408eaa0ee8ed63bc74843789b8f813b9c277078602f61f
    docker:
      - image: ${DOCKER_REGISTRY_URL}/build/node:12
    steps:
      - checkout

      - run:
          name: NPM Login
          command: release-manager login npm

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - /node_modules

      - run:
          name: Run Linting
          command: npm run lint

      - run:
          name: Run Tests
          command: npm test

      - run:
          name: Publish to NPM Registry
          command: release-manager publish npm

      - setup_remote_docker

      - run:
          name: Publish to Docker
          command: release-manager publish docker

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build:
          context: release-manager
